In [175]:
import string
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize, regexp_tokenize
from autocorrect import spell
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from itertools import chain
from gensim.models import KeyedVectors
import numpy as np
from numpy.random import randn
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import time
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB                                                                
from sklearn.cross_validation import train_test_split 
from sklearn.metrics import accuracy_score

In [2]:
df_train = pd.read_csv("train.csv")

In [3]:
sentence_1a = df_train['question1']
sentence_1b = df_train['question2']
is_duplicate = df_train['is_duplicate']
id_ = df_train['id']

In [4]:
model = KeyedVectors.load_word2vec_format("GoogleNews-vectors-negative300.bin.gz",binary=True)

In [54]:
STOPWORDS = stopwords.words('english')
tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')
wordnet_lemmatizer = WordNetLemmatizer()
punctuation_list = list(string.punctuation)

'''
def spell_digits(text):
    translation = {
        '0': 'zero',
        '1': 'one',
        '2': 'two',
        '3': 'three',
        '4': 'four',
        '5': 'five',
        '6': 'six',
        '7': 'seven',
        '8': 'eight',
        '9': 'nine',
    }
    return translate(text, translation)
'''

def spelling_correction(question):
    question_updated = ""
    #for token in word_tokenize(question):
    for token in tokenizer.tokenize(question):
        word = ''.join(ch for ch in token if ch not in punctuation_list and ch.isalpha())
        question_updated =  question_updated + spell(word) + " "
    return question_updated

def remove_stopword_questions(question):
    temp_list = [token for token in tokenizer.tokenize(question) if token not in stopwords.words('english')]
    return ' '.join(temp_list)

def get_preprocessed_tokens(question):  
    question = spelling_correction(question)
    question = question.lower()
    question = remove_stopword_questions(question)
    question = [word for word in tokenizer.tokenize(question)]
    return question

In [6]:
def lemmatize_tokens(question):
    joined_tokens = []
    for token in get_preprocessed_tokens(question):
        token_lemma = wordnet_lemmatizer.lemmatize(token)
        joined_tokens.append(token_lemma)
    return joined_tokens

In [ ]:
df_word2vec = pd.DataFrame()
for c_id, q1 , q2, label in zip(id_, sentence_1a, sentence_1b, is_duplicate):
    questions = [q1, q2]
    try:
        lemmas = []
        for question in questions:
            lemmas.append(lemmatize_tokens(question))

        embeddings = []
        for lemma in lemmas:
            vec_word = np.zeros(300)
            no_of_words = 0.0
            for word in lemma:
                #if word in model.vocab:
                vec_word += model.word_vec(word)
                no_of_words += 1
            '''
            if no_of_words == 0:
                vec_word = np.zeros(300)
            else:
            '''
            vec_word = vec_word/no_of_words

            embeddings.append(vec_word.reshape(1,-1))

        cos = cosine_similarity(embeddings[0],embeddings[1])[0]
        df_word2vec_temp = pd.DataFrame({'embedding1': [embeddings[0][0]], 'embedding2': [embeddings[1][0]], \
                                         'cosine': cos, 'is_duplicate': label, \
                                        'question1': q1, 'question2': q2})
        df_word2vec = pd.concat([df_word2vec, df_word2vec_temp])
        
    except:
        print c_id

In [94]:
df_word2vec.tail(100)

cosine                                         embedding1  \
0   0.721876  [-0.179036458333, -0.17138671875, -0.059082031...   
0   0.748472  [-0.083740234375, 0.106689453125, 0.1234537760...   
0   0.284414  [0.0281982421875, 0.0219116210938, -0.02606201...   
0   0.822010  [0.039111328125, 0.00260009765625, 0.124951171...   
0   0.934587  [0.0511779785156, 0.0625, -0.0662536621094, 0....   
0   0.685158  [-0.110961914062, -0.060546875, 0.03876953125,...   
0   0.924393  [0.00203450520833, 0.064951578776, 0.103719075...   
0   0.565857  [0.124267578125, -0.0167643229167, -0.21468098...   
0   0.891367  [-0.0788922991071, 0.0617327008929, -0.0268445...   
0   0.522218  [0.082275390625, -0.012451171875, 0.0616455078...   
0   1.000000  [0.0960693359375, 0.000244140625, -0.020019531...   
0   0.726125  [-0.176025390625, 0.0908203125, -0.07554626464...   
0   0.720714  [0.0116238064236, 0.0340983072917, -0.01360999...   
0   0.792409  [0.00113932291667, 0.00880940755208, 0.0085042...   
0   0.190171  [0.0876617431641, -0.0757242838542, -0.0939534...   
0   0.859779  [0.0943196614583, 0.02685546875, -0.0639038085...   
0   0.900437  [-0.05908203125, -0.0271809895833, 0.130615234...   
0   0.443093  [0.0931640625, -0.0475952148437, -0.0107147216...   
0   0.941884  [0.0483978271484, 0.05654296875, -0.0464355468...   
0   0.862568  [0.151123046875, 0.13623046875, -0.16589355468...   
0   0.175358  [-0.0175170898438, 0.194376627604, -0.05257161...   
0   0.301491  [0.0902099609375, 0.0682779947917, 0.018880208...   
0   0.880518  [0.165201822917, -0.123982747396, 0.0111490885...   
0   0.706328  [-0.0664672851562, 0.0596974690755, -0.0052897...   
0   0.983090  [0.140411376953, 0.0207170758929, 0.0177176339...   
0   0.644491  [-0.0639404296875, 0.0217529296875, 0.10131835...   
0   0.989283  [-0.0366516113281, 0.0424011230469, 0.03657226...   
0   0.786525  [0.064208984375, 0.2001953125, -0.034515380859...   
0   0.940111  [0.0997721354167, -0.0935872395833, -0.0696614...   
0   0.617976  [0.0537719726562, -0.0103759765625, -0.0294596...   
..       ...                                                ...   
0   0.273553  [0.00521573153409, -0.0199973366477, 0.0214621...   
0   0.794263  [0.00263671875, -0.01162109375, 0.026440429687...   
0   0.722102  [0.041576385498, -0.0452270507812, -0.04121017...   
0   0.716316  [-0.0151611328125, -0.028857421875, -0.0101562...   
0   0.916993  [0.074348449707, 0.0747222900391, 0.0450439453...   
0   0.883566  [-0.04208984375, -0.00050048828125, 0.07835693...   
0   0.652481  [-0.0707092285156, -0.052978515625, 0.08569335...   
0   0.922843  [0.133422851562, 0.088330078125, -0.0156555175...   
0   0.774692  [0.0218505859375, -0.0708821614583, -0.0581665...   
0   0.569607  [-0.0321180555556, 0.0571424696181, 0.00754123...   
0   0.807408  [0.0248006184896, 0.016357421875, 0.056640625,...   
0   0.646222  [0.114532470703, 0.0554504394531, 0.0045369466...   
0   0.873113  [0.0872268676758, 0.0486450195312, -0.02481842...   
0   0.519690  [0.111633300781, 0.0374755859375, -0.014049530...   
0   0.835086  [-0.00796508789062, -0.015625, 0.0250854492188...   
0   1.000000  [0.1142578125, -0.1162109375, 0.0478515625, -0...   
0   0.591984  [0.08642578125, -0.010752360026, 0.14841715494...   
0   0.659333  [0.0316074916295, -0.0172119140625, 0.09784807...   
0   0.845631  [-0.0125610351563, 0.003515625, -0.02349700927...   
0   0.683830  [-0.0185466766357, -0.019921875, -0.0125976562...   
0   0.662912  [-0.01748046875, 0.129833984375, 0.04427490234...   
0   0.388276  [0.263671875, -0.279296875, 0.0107421875, -0.1...   
0   0.585481  [-0.096435546875, 0.0511067708333, 0.074483235...   
0   0.954203  [-0.064453125, -0.0446411132812, 0.00327148437...   
0   0.885354  [-0.0801086425781, 0.0947265625, -0.0973396301...   
0   0.747326  [-0.0403878348214, 0.0353655133929, 0.01763044...   
0   0.868354  [0.106462751116, -0.0212925502232, 0.038827351...   
0   0.870961  [-0.0922037760417, 0.0543823242188, 0.1

In [95]:
df_word2vec.to_csv("embeddings_without_stopwords_words_deleted.csv", index=False)
df_word2vec_org = df_word2vec

In [117]:
df_word2vec_org = df_word2vec

In [118]:
df_word2vec_org

cosine                                         embedding1  \
0   0.931028  [-0.117213657924, 0.0111607142857, -0.02437046...   
0   0.777991  [0.0597330729167, -0.00455220540365, 0.0519612...   
0   0.345831  [-0.0293782552083, 0.0596516927083, -0.2041854...   
0   0.633217  [-0.0685180664062, 0.0075439453125, 0.08830566...   
0   0.935385  [-0.067626953125, -0.1103515625, -0.0213623046...   
0   1.000000  [0.155029296875, -0.0684204101562, 0.144775390...   
0   0.907822  [-0.0890808105469, -0.0761413574219, -0.057983...   
0   1.000000  [0.0268707275391, 0.0444030761719, -0.03454589...   
0   0.945967  [0.0632781982422, 0.0108642578125, 0.006732940...   
0   0.970117  [-0.120119730632, 0.0572408040365, 0.093526204...   
0   0.705628  [-0.096435546875, 0.0696166992187, 0.124182128...   
0   1.000000  [0.0140380859375, -0.0093994140625, -0.1118164...   
0   0.868886  [0.09423828125, 0.00660705566406, 0.1005371093...   
0   0.850430  [0.0473251342773, -0.0543594360352, 0.00787353...   
0   0.801928  [-0.00634765625, 0.00713500976563, 0.009716796...   
0   0.749116  [-0.0586344401042, 0.173502604167, -0.08064778...   
0   0.806013  [0.223307291667, -0.0498046875, -0.05200195312...   
0   1.000000  [-0.0297037760417, 0.00699869791667, 0.0841471...   
0   0.534438  [0.202840169271, 0.0302734375, 0.139485677083,...   
0   0.744119  [-0.0282796223958, 0.0198567708333, 0.09933471...   
0   0.954238  [-0.0106048583984, 0.0758870442708, -0.0166015...   
0   0.871329  [0.015380859375, -0.146728515625, -0.099121093...   
0   0.725157  [-0.0109375, 0.05263671875, -0.0109375, 9.7656...   
0   0.923731  [0.02880859375, 0.003076171875, 0.049755859375...   
0   0.743021  [-0.0411376953125, 0.103820800781, 0.052276611...   
0   0.824816  [0.042822265625, 0.021923828125, 0.09137268066...   
0   0.827863  [0.0117885044643, 0.0434221540179, -0.06272670...   
0   0.941930  [0.109723772321, 0.0575125558036, 0.0026506696...   
0   0.249566  [-0.00323994954427, 0.00637817382812, 0.019551...   
0   0.841682  [-0.00688552856445, -0.0465087890625, 0.053833...   
..       ...                                                ...   
0   0.273553  [0.00521573153409, -0.0199973366477, 0.0214621...   
0   0.794263  [0.00263671875, -0.01162109375, 0.026440429687...   
0   0.722102  [0.041576385498, -0.0452270507812, -0.04121017...   
0   0.716316  [-0.0151611328125, -0.028857421875, -0.0101562...   
0   0.916993  [0.074348449707, 0.0747222900391, 0.0450439453...   
0   0.883566  [-0.04208984375, -0.00050048828125, 0.07835693...   
0   0.652481  [-0.0707092285156, -0.052978515625, 0.08569335...   
0   0.922843  [0.133422851562, 0.088330078125, -0.0156555175...   
0   0.774692  [0.0218505859375, -0.0708821614583, -0.0581665...   
0   0.569607  [-0.0321180555556, 0.0571424696181, 0.00754123...   
0   0.807408  [0.0248006184896, 0.016357421875, 0.056640625,...   
0   0.646222  [0.114532470703, 0.0554504394531, 0.0045369466...   
0   0.873113  [0.0872268676758, 0.0486450195312, -0.02481842...   
0   0.519690  [0.111633300781, 0.0374755859375, -0.014049530...   
0   0.835086  [-0.00796508789062, -0.015625, 0.0250854492188...   
0   1.000000  [0.1142578125, -0.1162109375, 0.0478515625, -0...   
0   0.591984  [0.08642578125, -0.010752360026, 0.14841715494...   
0   0.659333  [0.0316074916295, -0.0172119140625, 0.09784807...   
0   0.845631  [-0.0125610351563, 0.003515625, -0.02349700927...   
0   0.683830  [-0.0185466766357, -0.019921875, -0.0125976562...   
0   0.662912  [-0.01748046875, 0.129833984375, 0.04427490234...   
0   0.388276  [0.263671875, -0.279296875, 0.0107421875, -0.1...   
0   0.585481  [-0.096435546875, 0.0511067708333, 0.074483235...   
0   0.954203  [-0.064453125, -0.0446411132812, 0.00327148437...   
0   0.885354  [-0.0801086425781, 0.0947265625, -0.0973396301...   
0   0.747326  [-0.0403878348214, 0.0353655133929, 0.01763044...   
0   0.868354  [0.106462751116, -0.0212925502232, 0.038827351...   
0   0.870961  [-0.0922037760417, 0.0543823242188, 0.1

In [126]:
threshold_list = [0.5 , 0.6 , 0.7, 0.8, 0.9]
cosine = df_word2vec_org['cosine']
y_true = df_word2vec_org['is_duplicate']
for threshold in threshold_list:
    is_dup_pred = []
    for cos in cosine:
        if cos > threshold:
            is_dup_pred.append(1)
        else:
            is_dup_pred.append(0)
        
    df_word2vec_org['is_dup_pred'+ str(threshold)] = is_dup_pred
    y_pred = is_dup_pred
    target_names = [0, 1]
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=target_names).ravel()
    print confusion_matrix(y_true, y_pred, labels=target_names)
    accuracy = float(tn + tp)/(tn + fp + fn + tp)
    print "Accuracy: ", accuracy
    print classification_report(y_true, y_pred)

[[ 32072 172294]
 [   647 134277]]
Accuracy:  0.490285596392
             precision    recall  f1-score   support

          0       0.98      0.16      0.27    204366
          1       0.44      1.00      0.61    134924

avg / total       0.76      0.49      0.40    339290

[[ 50450 153916]
 [  2905 132019]]
Accuracy:  0.537796575201
             precision    recall  f1-score   support

          0       0.95      0.25      0.39    204366
          1       0.46      0.98      0.63    134924

avg / total       0.75      0.54      0.49    339290

[[ 83996 120370]
 [ 11982 122942]]
Accuracy:  0.609914822129
             precision    recall  f1-score   support

          0       0.88      0.41      0.56    204366
          1       0.51      0.91      0.65    134924

avg / total       0.73      0.61      0.60    339290

[[127072  77294]
 [ 37859  97065]]
Accuracy:  0.660605971293
             precision    recall  f1-score   support

          0       0.77      0.62      0.69    204366
    

In [121]:
df_word2vec_org.shape

(339290, 11)

In [127]:
df_word2vec_org.to_csv("embeddings_without_stopwords_words_deleted.csv", index=False)

In [184]:
embedding1 = df_word2vec_org['embedding1']
embedding2 = df_word2vec_org['embedding2']
train_label = df_word2vec_org['is_duplicate']
train_questions = embedding1 + embedding2

In [177]:
type(embedding1[0:5]), embedding2[0:5]

(pandas.core.series.Series,
 0    [-0.0976867675781, 0.0249837239583, -0.0301920...
 0    [0.00126953125, 0.0135009765625, -0.0549804687...
 0    [0.148217773438, -0.021923828125, 0.0549316406...
 0    [-0.05009765625, 0.14853515625, 0.038427734375...
 0    [-0.052001953125, -0.03759765625, -0.026855468...
 Name: embedding2, dtype: object)

In [139]:
train_questions

0    [-0.214900425502, 0.036144438244, -0.054562523...
0    [0.0610026041667, 0.00894877115885, -0.0030192...
0    [0.118839518229, 0.0377278645833, -0.149253845...
0    [-0.118615722656, 0.156079101562, 0.1267333984...
0    [-0.11962890625, -0.14794921875, -0.0482177734...
dtype: object

In [182]:
def naive_bayer(x_train_matrix, x_test_matrix, y_train, y_test):    #NAIVE BAYERS MODEL
                                                                    
    nb = GaussianNB()
    nb.fit(x_train_matrix, y_train)                                 #train the model
    y_pred = nb.predict(x_test_matrix)                              #make predictions for X_test
    print ("Naive Byers Model score: " + str(accuracy_score(y_test, y_pred)))         
    print ("Naive Byers Model confusion matrix:")
    print (confusion_matrix(y_test, y_pred))

def logistic_regression(x_train_matrix, x_test_matrix, y_train, y_test): 
    logReg = LogisticRegression(C=0.85)
    logReg.fit(x_train_matrix, y_train)
    y_pred_log = logReg.predict(x_test_matrix)
    print ("Logistic Regression score: "+ str(accuracy_score(y_test, y_pred_log)))
    print ("Logistic Regression confusion matrix:")
    print (confusion_matrix(y_test, y_pred_log))

def linear_svm(x_train_matrix, x_test_matrix, y_train, y_test):
    svm1 = LinearSVC(C=1)
    svm1.fit(x_train_matrix, y_train)
    y_pred_svc = svm1.predict(x_test_matrix)
    print ("SVC score: " + str(accuracy_score(y_test, y_pred_svc)))
    print ("SVC confusionmatrix:")
    print (confusion_matrix(y_test, y_pred_svc))

In [ ]:
start_time = time.time()


train_question_label = zip(train_questions,train_label) 
train_df = pd.DataFrame(train_question_label, columns=['embedding', 'label'])
X = train_df.embedding
Y = train_df.label

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=1)

preprocessing_time = time.time()
print("--- start -> preprocessing:%s seconds ---" % (preprocessing_time - start_time))

X_train = np.matrix(X_train.tolist())
#Y_train = np.matrix(Y_train.tolist())
X_test = np.matrix(X_test.tolist())
#Y_test = np.matrix(Y_test.tolist())
naive_bayer(X_train, X_test, Y_train, Y_test)
naive_bayer_time = time.time() 
print("--- preprocessing -> naive bayer :%s seconds ---" % (naive_bayer_time - preprocessing_time))

print ("-------------------------------------------")

logistic_regression(X_train, X_test, Y_train, Y_test)
logistic_regression_time = time.time()
print("--- niave bayer -> logistic regression :%s seconds ---" % (logistic_regression_time - naive_bayer_time))

print ("-------------------------------------------")

linear_svm(X_train, X_test, Y_train, Y_test)
linear_svm_time = time.time()
print("--- logistic regression -> linear svm :%s seconds ---" % (linear_svm_time - logistic_regression_time))
print("--- TOTAL TIME: %s seconds ---" % (time.time() - start_time))

--- start -> preprocessing:0.460880994797 seconds ---
Naive Byers Model score: 0.618499699374
Naive Byers Model confusion matrix:
[[36178 14946]
 [17414 16285]]
--- preprocessing -> naive bayer :5.19384503365 seconds ---
-------------------------------------------
Logistic Regression score: 0.677917545949
Logistic Regression confusion matrix:
[[43475  7649]
 [19671 14028]]
--- niave bayer -> logistic regression :17.6321380138 seconds ---
-------------------------------------------
